<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LangVersion>12</LangVersion>
    <RootNamespace>MacDock.UI</RootNamespace>
    <AssemblyName>MacDock</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.0.131" />
    <PackageReference Include="NLog" Version="6.2.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.30" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MacDock.Core\MacDock.Core.csproj" />
    <ProjectReference Include="..\MacDock.Animations\MacDock.Animations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.IO" />
  </ItemGroup>

</Project>
